In [1]:
import numpy as np

import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression

# f(x) = w1x + w2x**2 + w3x**3 + …… + b
from sklearn.preprocessing import PolynomialFeatures

# 管道，pipeline
from sklearn.pipeline import Pipeline

In [2]:
# 年份
X = (np.arange(2009,2020) - 2008).reshape(-1,1)
# 销售额
y = np.array([0.52,9.36,52,191,350,571,912,1207,1682,2135,2684])

In [5]:
poly = PolynomialFeatures(degree=3)

In [7]:
X_poly = poly.fit_transform(X)
X_poly.astype(np.int16)

array([[   1,    1,    1,    1],
       [   1,    2,    4,    8],
       [   1,    3,    9,   27],
       [   1,    4,   16,   64],
       [   1,    5,   25,  125],
       [   1,    6,   36,  216],
       [   1,    7,   49,  343],
       [   1,    8,   64,  512],
       [   1,    9,   81,  729],
       [   1,   10,  100, 1000],
       [   1,   11,  121, 1331]], dtype=int16)

In [9]:
linear_model = LinearRegression(fit_intercept=False)

linear_model.fit(X_poly,y)

linear_model.coef_[::-1]

array([  0.12714841,  27.94904429, -84.07507382,  58.79636364])

### 管道一步步处理数据思想

In [11]:
pipeline = Pipeline([('polynomialFeatures',PolynomialFeatures(degree = 3)),
                     ('linear_model',LinearRegression(fit_intercept = False))])

In [13]:
pipeline.fit(X,y)

Pipeline(memory=None,
         steps=[('polynomialFeatures',
                 PolynomialFeatures(degree=3, include_bias=True,
                                    interaction_only=False, order='C')),
                ('linear_model',
                 LinearRegression(copy_X=True, fit_intercept=False, n_jobs=None,
                                  normalize=False))],
         verbose=False)

In [18]:
pipeline.steps[1][1].coef_

array([ 58.79636364, -84.07507382,  27.94904429,   0.12714841])

In [14]:
pipeline.predict([[12]])

array([3294.27030303])