In [1]:
import numpy as np

In [7]:
np.random.seed(42) # 随机种子
arr = np.random.randint(1,10,size=(3,3))
arr   # 创建数组

array([[7, 4, 8],
       [5, 7, 3],
       [7, 8, 5]])

In [8]:
arr.sort()   # 直接排序
arr

array([[4, 7, 8],
       [3, 5, 7],
       [5, 7, 8]])

In [9]:
arr.sort(axis = 1)  # 延横轴排序
arr

array([[4, 7, 8],
       [3, 5, 7],
       [5, 7, 8]])

In [11]:
arr.sort(axis = 0)  # 延纵轴排序
arr

array([[3, 5, 7],
       [4, 7, 8],
       [5, 7, 8]])

#### 去重与重复数据
#####  统计分析中的重复数据就是脏数据的一种


In [12]:
# 通过unique函数找出数组中的唯一值并返回已排序的结果
names = np.array(['小明','小花','小明','小黄','小小兰','小白','小明',])
names

array(['小明', '小花', '小明', '小黄', '小小兰', '小白', '小明'], dtype='<U3')

In [13]:
# 去重
np.unique(names)

array(['小小兰', '小明', '小白', '小花', '小黄'], dtype='<U3')

In [14]:
# 数据加重 可以采用tile和repeat函数实现数据重复,前者对整个数组实现重复，后者对数组中的每个元素进行重复操作
np.tile(names,3)

array(['小明', '小花', '小明', '小黄', '小小兰', '小白', '小明', '小明', '小花', '小明', '小黄',
       '小小兰', '小白', '小明', '小明', '小花', '小明', '小黄', '小小兰', '小白', '小明'],
      dtype='<U3')

#### 统计函数的分析之聚合运算

In [16]:
arr = np.arange(20).reshape(4,5)
arr # 创建数组

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [17]:
np.sum(arr)  # 计算数组的和

190

In [18]:
arr.sum(axis = 0)  # 延纵轴求和

array([30, 34, 38, 42, 46])

In [19]:
arr.sum(axis = 1)   # 眼横轴求和

array([10, 35, 60, 85])

In [20]:
np.mean(arr)   # 计算平均值

9.5

In [21]:
arr.mean(axis = 0) # 延纵轴计算均值


array([ 7.5,  8.5,  9.5, 10.5, 11.5])

In [22]:
arr.mean(axis = 1) # 延横轴计算均值

array([ 2.,  7., 12., 17.])

In [23]:
np.std(arr)  # 计算标准差

5.766281297335398

In [24]:
np.var(arr)   # 计算方差

33.25

In [25]:
np.min(arr)   # 计算最小值

0

In [26]:
np.max(arr)   # 计算最大值

19

In [27]:
np.argmin(arr)   # 计算数组最小值的索引

0

In [29]:
np.argmax(arr)  # 返回数组的最大值的索引

19

#### 非聚合运算

In [30]:
arr = np.arange(2,10)
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.cumsum(arr)   # 计算所有元素的累计和

array([ 2,  5,  9, 14, 20, 27, 35, 44], dtype=int32)

In [32]:
np.cumprod(arr)   # 计算所有元素的累计积

array([     2,      6,     24,    120,    720,   5040,  40320, 362880],
      dtype=int32)