In [1]:
import numpy as np 

#### 矩阵

In [2]:
# 使用mat或matrix创建矩阵
mat = np.mat("1 2 3;4 5 6; 7 8 9")   # 使用分号隔开数据
mat

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
## 使用bmt创建矩阵，将小矩阵组合成大矩阵
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
arr1 = arr*3
arr1

array([[3., 0., 0.],
       [0., 3., 0.],
       [0., 0., 3.]])

In [6]:
# 合并矩阵(bmat)
np.bmat("arr, arr1;arr1,arr")

matrix([[1., 0., 0., 3., 0., 0.],
        [0., 1., 0., 0., 3., 0.],
        [0., 0., 1., 0., 0., 3.],
        [3., 0., 0., 1., 0., 0.],
        [0., 3., 0., 0., 1., 0.],
        [0., 0., 3., 0., 0., 1.]])

#### 矩阵计算

In [7]:
mat = np.mat("1 2 3;4 5 6; 7 8 9")
mat

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [8]:
mat1 = mat *3   # 矩阵与数相乘
mat1

matrix([[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27]])

In [9]:
mat+mat1 # 矩阵相加

matrix([[ 4,  8, 12],
        [16, 20, 24],
        [28, 32, 36]])

In [10]:
mat1 - mat  # 矩阵相减


matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [11]:
mat*mat1    # 矩阵相乘

matrix([[ 90, 108, 126],
        [198, 243, 288],
        [306, 378, 450]])

In [13]:
np.multiply(mat1,mat)    # 矩阵对应元素相乘

matrix([[  3,  12,  27],
        [ 48,  75, 108],
        [147, 192, 243]])

#### 矩阵属性

In [14]:
mat1.T     # T转置

matrix([[ 3, 12, 21],
        [ 6, 15, 24],
        [ 9, 18, 27]])

In [15]:
mat1.H     # 共轭转置

matrix([[ 3, 12, 21],
        [ 6, 15, 24],
        [ 9, 18, 27]])

In [17]:
mat.I    # 逆矩阵

matrix([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
        [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
        [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [18]:
mat1.A   # 返回二维数组的视图

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

#### ufunc函数
#####  通用函数，是一种可以对数组中所有元素进行操作的函数，有四则，比较和逻辑运算


In [19]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [20]:
x+y  # 数组加减乘除

array([5, 7, 9])

In [21]:
x-y

array([-3, -3, -3])

In [22]:
x *y

array([ 4, 10, 18])

In [23]:
x/y

array([0.25, 0.4 , 0.5 ])

In [24]:
x**y   # 数组幂运算

array([  1,  32, 729], dtype=int32)

##### 数组的比较

In [25]:
x<y

array([ True,  True,  True])

In [26]:
x == y

array([False, False, False])

In [27]:
np.all(x == y)   # np.all()表示逻辑and

False

In [29]:
np.any(x==y)      # np.any()  表示逻辑or

False