In [1]:
import numpy as np

### 广播
##### 是指不同形状的数组之间执行算术运算的方式
#### 遵循原则
##### 让所有的数组向其中shape最长的数组看齐，shape中不足的部分通过前面加1 补齐
#####  输出数组的shape是输入数组shape各轴上的最大值
#####  输入数组的某个轴和输出数组的对应轴的长度相同或者为1，则可以进行计算
#####  当输入数组的某个轴的长度为1，沿此轴运算时使用此轴上的第一组值

In [2]:
arr = np.array([[0,0,0],[1,1,1],[2,2,2],[3,3,3]])
arr

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [3]:
arr.shape

(4, 3)

In [4]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [5]:
arr1.shape

(3,)

In [6]:
arr1+arr    # 一维数组相加的广播

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [7]:
# 二维数组相加广播原理
arr1 = np.array([[0,0,0],[1,1,1],[2,2,2],[3,3,3]])
arr1

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [9]:
arr2 = np.array([1,2,3,4]).reshape(4,1)
arr2

array([[1],
       [2],
       [3],
       [4]])

In [10]:
arr2.shape

(4, 1)

In [11]:
arr1*arr2

array([[ 0,  0,  0],
       [ 2,  2,  2],
       [ 6,  6,  6],
       [12, 12, 12]])