In [1]:
import numpy as np

from sklearn.decomposition import PCA

from sklearn import datasets

d:\python3.6.8\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [29]:
X,y = datasets.load_iris(True)
pca = PCA(n_components=2,whiten=True)
pca.fit(X)
X_pca = pca.transform(X)
X_pca[:5]

array([[-1.30533786,  0.64836932],
       [-1.31993521, -0.35930856],
       [-1.40496732, -0.29424412],
       [-1.33510889, -0.64613986],
       [-1.32702321,  0.6633044 ]])

* 去平均值(即去中心化)，即每一位特征减去各自的平均值
* 计算协方差矩阵
* 用特征值分解方法求协方差矩阵的特征值与特征向量
* 对特征值从大到小排序，选择其中最大的k个。然后将其对应的k个特征向量分别作为行向量组成特征向量矩阵P
* 将数据转换到k个特征向量构建的新空间中，即X_pca=XP

In [8]:
# 第一步，去中心化，减去平均值
B = X - X.mean(axis = 0)
B.shape

(150, 4)

In [10]:
# 第二步，协方差矩阵
C = np.cov(B,rowvar=False)
C

array([[ 0.68569351, -0.042434  ,  1.27431544,  0.51627069],
       [-0.042434  ,  0.18997942, -0.32965638, -0.12163937],
       [ 1.27431544, -0.32965638,  3.11627785,  1.2956094 ],
       [ 0.51627069, -0.12163937,  1.2956094 ,  0.58100626]])

In [33]:
np.linalg.svd(C)

(array([[-0.36138659, -0.65658877,  0.58202985,  0.31548719],
        [ 0.08452251, -0.73016143, -0.59791083, -0.3197231 ],
        [-0.85667061,  0.17337266, -0.07623608, -0.47983899],
        [-0.3582892 ,  0.07548102, -0.54583143,  0.75365743]]),
 array([4.22824171, 0.24267075, 0.0782095 , 0.02383509]),
 array([[-0.36138659,  0.08452251, -0.85667061, -0.3582892 ],
        [-0.65658877, -0.73016143,  0.17337266,  0.07548102],
        [ 0.58202985, -0.59791083, -0.07623608, -0.54583143],
        [ 0.31548719, -0.3197231 , -0.47983899,  0.75365743]]))

In [12]:
# 第三步，求解了特征值和特征向量
eigenvalues,eigenvectors = np.linalg.eig(C)
display(eigenvalues,eigenvectors)

array([4.22824171, 0.24267075, 0.0782095 , 0.02383509])

array([[ 0.36138659, -0.65658877, -0.58202985,  0.31548719],
       [-0.08452251, -0.73016143,  0.59791083, -0.3197231 ],
       [ 0.85667061,  0.17337266,  0.07623608, -0.47983899],
       [ 0.3582892 ,  0.07548102,  0.54583143,  0.75365743]])

In [15]:
# 第四步，筛选特征值，取出，特征值所对应的特征向量
P = eigenvectors[:,:2]
P

array([[ 0.36138659, -0.65658877],
       [-0.08452251, -0.73016143],
       [ 0.85667061,  0.17337266],
       [ 0.3582892 ,  0.07548102]])

In [19]:
# 第五步，将数据转换到k个特征向量构建的新空间中，即X_pca=XP

V = X.dot(P)

In [21]:
V = (V - V.mean(axis = 0))/V.std(axis = 0)
V[:5]

array([[-1.30971087, -0.65054141],
       [-1.32435711,  0.36051227],
       [-1.40967409,  0.29522986],
       [-1.33958163,  0.64830449],
       [-1.33146886, -0.66552653]])

In [22]:
X_pca[:5]

array([[-1.30533786,  0.64836932],
       [-1.31993521, -0.35930856],
       [-1.40496732, -0.29424412],
       [-1.33510889, -0.64613986],
       [-1.32702321,  0.6633044 ]])

In [23]:
# 第五步，使用去中心化的数据，进行映射
M = B.dot(P)

M = (M - M.mean(axis = 0))/M.std(axis = 0)
M[:5]

array([[-1.30971087, -0.65054141],
       [-1.32435711,  0.36051227],
       [-1.40967409,  0.29522986],
       [-1.33958163,  0.64830449],
       [-1.33146886, -0.66552653]])

In [24]:
X_pca[:5]

array([[-1.30533786,  0.64836932],
       [-1.31993521, -0.35930856],
       [-1.40496732, -0.29424412],
       [-1.33510889, -0.64613986],
       [-1.32702321,  0.6633044 ]])

In [30]:
W = B.dot(P)
W[:5]

array([[-2.68412563, -0.31939725],
       [-2.71414169,  0.17700123],
       [-2.88899057,  0.14494943],
       [-2.74534286,  0.31829898],
       [-2.72871654, -0.32675451]])

In [28]:
X_pca[:5]

array([[-2.68412563,  0.31939725],
       [-2.71414169, -0.17700123],
       [-2.88899057, -0.14494943],
       [-2.74534286, -0.31829898],
       [-2.72871654,  0.32675451]])

In [31]:
Z = (W - W.mean(axis = 0))/W.std(axis = 0)
Z[:5]

array([[-1.30971087, -0.65054141],
       [-1.32435711,  0.36051227],
       [-1.40967409,  0.29522986],
       [-1.33958163,  0.64830449],
       [-1.33146886, -0.66552653]])

In [32]:
X_pca[:5]

array([[-1.30533786,  0.64836932],
       [-1.31993521, -0.35930856],
       [-1.40496732, -0.29424412],
       [-1.33510889, -0.64613986],
       [-1.32702321,  0.6633044 ]])