* 计算数据总的散度矩阵S_t
* 计算数据类内散度矩阵S_w
* 计算类间散度矩阵S_b
* 特征值和特征向量计算
* 筛选特征向量，进行矩阵运算返回输出结果

In [1]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

from sklearn import datasets

# 线性代数，功能更加强大
from scipy import linalg

In [2]:
X,y = datasets.load_iris(True)


In [12]:
X.shape[1]

4

In [15]:
np.unique(y)

array([0, 1, 2])

In [13]:
min(3 - 1, X.shape[1])

2

In [11]:
# eigen 特征值
lda = LinearDiscriminantAnalysis(n_components=4,solver='eigen')

lda.fit(X,y)

X_lda = lda.transform(X)
X_lda[:5]

array([[6.01716893, 7.03257409],
       [5.0745834 , 5.9344564 ],
       [5.43939015, 6.46102462],
       [4.75589325, 6.05166375],
       [6.08839432, 7.24878907]])

In [39]:
# 第一步，总的散度矩阵total,协方差
S_t = np.cov(X.T,bias = 1)
S_t

array([[ 0.68112222, -0.04215111,  1.26582   ,  0.51282889],
       [-0.04215111,  0.18871289, -0.32745867, -0.12082844],
       [ 1.26582   , -0.32745867,  3.09550267,  1.286972  ],
       [ 0.51282889, -0.12082844,  1.286972  ,  0.57713289]])

In [35]:
# 第二步，类内散度矩阵 within
S_w = np.zeros_like(S_t)
for i in range(3):
    cond = y == i
    S_w += np.cov(X[cond],rowvar=False,bias = True)
S_w/=3
S_w

array([[0.259708  , 0.09086667, 0.164164  , 0.03763333],
       [0.09086667, 0.11308   , 0.05413867, 0.032056  ],
       [0.164164  , 0.05413867, 0.181484  , 0.041812  ],
       [0.03763333, 0.032056  , 0.041812  , 0.041044  ]])

In [36]:
# 第三步，类间的散度矩阵
S_b = S_t - S_w
S_b

array([[ 0.42141422, -0.13301778,  1.101656  ,  0.47519556],
       [-0.13301778,  0.07563289, -0.38159733, -0.15288444],
       [ 1.101656  , -0.38159733,  2.91401867,  1.24516   ],
       [ 0.47519556, -0.15288444,  1.24516   ,  0.53608889]])

In [37]:
# 第四步，特征特征向量
# scipy 线性代数模块计算
evals, evecs = linalg.eigh(S_b, S_w)
display(evals,evecs)

array([-1.84103303e-14,  1.18322589e-14,  2.85391043e-01,  3.21919292e+01])

array([[ 1.54162331, -2.82590065,  0.02434685,  0.83779794],
       [-2.49358543,  1.05970269,  2.18649663,  1.55005187],
       [-2.86907801,  1.01439507, -0.94138258, -2.22355955],
       [ 4.58628831,  0.45101349,  2.86801283, -2.83899363]])

In [34]:
X_lda[:5]

array([[6.01716893, 7.03257409],
       [5.0745834 , 5.9344564 ],
       [5.43939015, 6.46102462],
       [4.75589325, 6.05166375],
       [6.08839432, 7.24878907]])

In [38]:
# 第五步，获取特征所对应的特征向量
evecs = evecs[:,np.argsort(evals)[::-1]]
X.dot(evecs)[:,:2]

array([[  6.01716893,   7.03257409],
       [  5.0745834 ,   5.9344564 ],
       [  5.43939015,   6.46102462],
       [  4.75589325,   6.05166375],
       [  6.08839432,   7.24878907],
       [  5.65366246,   8.20566459],
       [  5.15936541,   7.08855228],
       [  5.55602799,   6.71735148],
       [  4.50067925,   5.70363331],
       [  5.291132  ,   5.77216652],
       [  6.35616273,   7.38303921],
       [  5.16611245,   6.61834385],
       [  5.27470297,   5.64522043],
       [  5.52287187,   5.91546178],
       [  7.82336533,   8.33114171],
       [  7.12473969,   9.49449347],
       [  6.54308629,   8.58221762],
       [  5.73326956,   7.31937537],
       [  6.03389602,   7.70751769],
       [  5.97592917,   7.8811861 ],
       [  5.44643525,   6.5388137 ],
       [  5.53702462,   7.94933772],
       [  6.64269897,   7.61560336],
       [  4.1883926 ,   7.17326384],
       [  4.49904458,   6.33592908],
       [  4.71365129,   5.74861457],
       [  4.76587331,   7.19681579],
 