In [2]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np

from sklearn.decomposition import PCA

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

from sklearn.decomposition import NMF

from sklearn import datasets

from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

In [3]:
X,y = datasets.load_iris(True)

In [29]:
pca = PCA(n_components=0.95,whiten=False)
X_pca = pca.fit_transform(X)
X_train,X_test,y_train,y_test = train_test_split(X_pca,y,random_state = 256)

gNB  = GaussianNB()
gNB.fit(X_train,y_train)
display(X_pca[:5])
gNB.score(X_test,y_test)

array([[-2.68412563,  0.31939725],
       [-2.71414169, -0.17700123],
       [-2.88899057, -0.14494943],
       [-2.74534286, -0.31829898],
       [-2.72871654,  0.32675451]])

0.868421052631579

In [30]:
H = pca.components_
W = X_pca
display(X[:5],W.dot(H)[:5])

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

array([[-7.60294366e-01,  4.60080598e-01, -2.35478628e+00,
        -9.85801646e-01],
       [-1.09707143e+00,  1.00166610e-01, -2.29443823e+00,
        -9.59087413e-01],
       [-1.13921462e+00,  1.38348265e-01, -2.44978303e+00,
        -1.02415318e+00],
       [-1.20112163e+00, -3.66359253e-04, -2.29667019e+00,
        -9.59601156e-01],
       [-7.71578225e-01,  4.69221526e-01, -2.39426155e+00,
        -1.00233342e+00]])

In [14]:
v = pca.explained_variance_
v

array([4.22824171, 0.24267075, 0.0782095 , 0.02383509])

In [16]:
v.cumsum()/v.sum()

array([0.92461872, 0.97768521, 0.99478782, 1.        ])

In [21]:
lda = LinearDiscriminantAnalysis(n_components=2)

# 类内的方差尽量小，类间方差尽量大
lda.fit(X,y)
X_lda = lda.transform(X)
X_train,X_test,y_train,y_test = train_test_split(X_lda,y,random_state = 256)
gNB = GaussianNB()
gNB.fit(X_train,y_train)
display(X_lda[:5])
gNB.score(X_test,y_test)

array([[ 8.06179978,  0.30042062],
       [ 7.12868772, -0.78666043],
       [ 7.48982797, -0.26538449],
       [ 6.81320057, -0.67063107],
       [ 8.13230933,  0.51446253]])

1.0

In [24]:
# Non-Negative Matrix Factorization
nmf = NMF(n_components=2)
X_nmf = nmf.fit_transform(X)

X_train,X_test,y_train,y_test = train_test_split(X_nmf,y,random_state = 256)

gNB = GaussianNB()
gNB.fit(X_train,y_train)
display(X_nmf[:5])
gNB.score(X_test,y_test)

array([[0.10666948, 1.32441671],
       [0.13650159, 1.1703995 ],
       [0.10290364, 1.21005821],
       [0.14288053, 1.12082689],
       [0.0985986 , 1.33211468]])

0.9736842105263158

In [26]:
W = X_nmf
H = nmf.components_
V = W.dot(H)
display(X[:5],V[:5])

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

array([[5.09591336, 3.50618857, 1.40120511, 0.20158305],
       [4.74639643, 3.19626659, 1.4607764 , 0.25795951],
       [4.68723639, 3.21605128, 1.30890071, 0.1944664 ],
       [4.61535011, 3.0890499 , 1.46297066, 0.27001439],
       [5.07551302, 3.50644084, 1.36356276, 0.18633077]])